def tampilkan_biodata():
    print("== Biodata Favian Rafiq Athallah ==")
    print()
    print("Nama           : Favian Rafiq Athallah")
    print("Nama Panggilan : Favian")
    print("NIM            : 1202407019")
    print("Alamat         : Nusukan, Banjarsari, Surakarta")
    print("Fakultas       : Sains dan Teknologi")
    print("Universitas    : Muhammadiyah PKU Surakarta")
    print("Jurusan        : Teknik Informatika")
    print("Agama          : Islam")
    print("Jenis Kelamin  : Laki-laki")
    print("Status         : Mahasiswa")
    print("Kegiatan Lain  : Nyocol coklat")
    print("Motivasi       : Pertumbuhan sejati dimulai saat kita berani menerima kelemahan diri sendiri")
    print()
    print("Terima kasih semua!")

tampilkan_biodata()